### ISSUE TITLE
Call to undefined function TamkeenTech\Payfort\Repositories\uuid_create()

### ISSUE THREAD

**Issue by MuhammadNouman** [TamkeenTech/laravel-payfort#1]
the error in title, Can you please check why it is happening? I just followed your steps in readme and tried tokenization.

**Comment by shreifelagamy** [comment]
I will check it and fix it soon

**Comment by MuhammadNouman** [comment]
thanks, I am using in Laravel9 PHP 8.1

**Comment by shreifelagamy** [comment]
@MuhammadNouman Please update the package to the latest version (2.0.5) it should be fixed, and let me know if you have any other issue, happy to help

**Comment by MuhammadNouman** [comment]
thank you for the fix, I am in process of implementing standard merchant page integration, not getting any idea about iframe implementation, can you guide (just a hint) ?

**Comment by shreifelagamy** [comment]
@MuhammadNouman yes sure, the idea here is when you call the tokenization process you will receive the following parameters: 
- url
- params
- forms   

From your front-end, you should be having a checkout page with card details so whenever the user enters his credit cards details and click submit you will need to append the params fields to the form and submit to the url provided to you from the tokenization

**Comment by MuhammadNouman** [comment]
nice, now facing this in return of the paymentPage api call
![image](https://user-images.githubusercontent.com/9676234/204233290-1534f2e9-081e-4b0e-8b5f-9958854092b7.png)

**Comment by MuhammadNouman** [comment]
nice, now getting signature mismatch erorr in response of the paymentPage post request when submitted

**Comment by shreifelagamy** [comment]
@MuhammadNouman do you mean after tokenization ? are you sure you defined the credentials correctly ? can you provide more details ?

**Comment by MuhammadNouman** [comment]
yes, my shastring generates like this REQ_PHRASEaccess_code=xxxxxxxxxxxxxlanguage=enmerchant_identifier=bf35b605merchant_reference=d11913da-6cee-4139-a8fa-7e9c1175c162service_command=TOKENIZATION1REQ_PHRASE

**Comment by shreifelagamy** [comment]
@MuhammadNouman can you var dump the response you receive from payfort after tokenization ?

**Comment by MuhammadNouman** [comment]
![image](https://user-images.githubusercontent.com/9676234/204479441-7a273597-76af-4b7c-9a7f-39fbf85bed33.png)
here is it,

**Comment by shreifelagamy** [comment]
@MuhammadNouman I checked the code, however about the sha string you shared i believe it's missing something, it missing the return_url and also I tested and it's working fine with me, you will need to try to generate the signature manually and test it with payfort and make sure that it's not a missing config from payfort, and please let me know if the package does have any issue.

I will close this issue as it's not longer related
